DROP TABLE GL_INTERFACE_TEMP;

CREATE TABLE GL_INTERFACE_TEMP (
    STATUS VARCHAR2(255),
    SET_OF_BOOKS_ID NUMBER,
    ACCOUNTING_DATE DATE,
    CURRENCY_CODE VARCHAR2(10),
    DATE_CREATED DATE,
    CREATED_BY NUMBER,
    ACTUAL_FLAG VARCHAR2(1),
    USER_JE_CATEGORY_NAME VARCHAR2(255),
    USER_JE_SOURCE_NAME VARCHAR2(255),
    SEGMENT1 VARCHAR2(255),
    SEGMENT2 VARCHAR2(255),
    SEGMENT3 VARCHAR2(255),
    SEGMENT4 VARCHAR2(255),
    SEGMENT5 VARCHAR2(255),
    ENTERED_DR NUMBER,
    ENTERED_CR NUMBER,
    ACCOUNTED_DR NUMBER,
    ACCOUNTED_CR NUMBER,
    GROUP_ID NUMBER,
    process_flag VARCHAR2(10),
    error_message VARCHAR2(2000)
);